version: "3.8"
services: 
  frontend:
    container_name: propsoft-frontend-side
    #build: . 
    image: 192.168.226.131/propsoft-client-side/nodejs
    restart:  always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
       - "3000:3000"
